<?php
/**
* A simple, clean and secure PHP Login Script / MINIMAL VERSION
* For more versions (one-file, advanced, framework-like) visit http://www.php-login.net
*
* Uses PHP SESSIONS, modern password-hashing and salting and gives the basic functions a proper login system needs.
*
* @author Panique
* @link https://github.com/panique/php-login-minimal/
* @license http://opensource.org/licenses/MIT MIT License
*/

// checking for minimum PHP version
if (version_compare(PHP_VERSION, '5.3.7', '<')) {
	exit("Sorry, Simple PHP Login does not run on a PHP version smaller than 5.3.7 !");
} else if (version_compare(PHP_VERSION, '5.5.0', '<')) {
	// if you are using PHP 5.3 or PHP 5.4 you have to include the password_api_compatibility_library.php
	// (this library adds the PHP 5.5 password hashing functions to older versions of PHP)
	require_once("lib/password_compatibility_library.php");
}

//Login already instanced
//$Login = new Login();

// ... ask if we are logged in here:
if ($login->isUserLoggedIn() == true) {
	// the user is logged in. you can do whatever you want here.
	// for demonstration purposes, we simply show the "you are logged in" view.
	?>


	<div class="container">
		<div class="row">
			<div class="page-header">
				<h1>About</h1>
			</div>
		</div>

		<div class="row">
			<ul>
				<li><a href="#con">Defined Constants</a></li>
				<li><a href="#var">Defined Variables</a></li>
				<li><a href="#func">Defined Functions</a></li>
			</ul>
		</div>

		<hr>

		<div class="row">
			<h2 id="con">Defined Constants</h2>
			<pre><?php print_r(get_defined_constants(true)['user']); ?></pre>
		</div>

		<div class="row">
			<h2 id="var">Defined Variables</h2>
			<pre><?php print_r(get_defined_vars()); ?></pre>
		</div>

		<div class="row">
			<h2 id="func">Defined Functions</h2>
			<pre><?php print_r(get_defined_functions()['user']); ?></pre>
		</div>
		
	</div>



	<?php

} else {
	// the user is not logged in. you can do whatever you want here.
	// for demonstration purposes, we simply show the "you are not logged in" view.
	header("location: ?page=login");
}
?>
