<?php
// create a login object. when this object is created, it will do all login/logout stuff automatically
// so this single line handles the entire login process. in consequence, you can simply ...
$login = new Login();

// ... ask if we are logged in here:
if ($login->isUserLoggedIn() == true) {
    // the user is logged in. you can do whatever you want here.
	?>

	<div class="row">
        <div class="col-md-10 col-md-offset-1">
          <!-- admin tab content here -->

			<?php
			if (isset($_POST['edit']) == "true") {
				/**
				 * Sanitize user data
				 */
				$id = $database->filter( $_POST['alert_id'] );
				$type = $database->filter( $_POST['alert_type'] );
				$message = $database->escape( $_POST['alert_message'] );

				if (!$type or !$message) {

					echo bsAlert('error', 'Alert not added, you must enter a title and body!');

				}
				else {

					/**
					 * Updating data
					 */
					//Fields and values to update
					$update = array(
						'type' => $type,
						'message' => $message
					);
					//Add the WHERE clauses
					$where_clause = array(
						'id' => $id
					);
					$updated = $database->update( 'alert', $update, $where_clause, 1 );
					if( $updated )
					{
						echo
						'
						<div class="alert alert-success">
							Your changes were successful! Redirecting you to the alert manager...
						</div>
						<script>setTimeout(function () {window.location.href = "index.php?page=admin/alert-manage";}, 1000);</script>
						';
					}
				}
			}
			elseif (isset($_GET['id'])) {
				/**
				 * Sanitize user data
				 */
				$id = $database->filter( $_GET['id'] );

				/**
				 * Retrieving a single row of data
				 */
				$query = "SELECT id, type, message, date, active FROM alert WHERE `id` = $id";
				if( $database->num_rows( $query ) > 0 )
				{
					list( $id, $type, $message, $date) = $database->get_row( $query );

					?>
					<div class="row">
						<div class="panel panel-default">
							<div class="panel-heading">
								<strong>Edit Alert</strong>
							</div><!-- / pannel heading -->

							<div class="panel-body" style="color:#000;">
								<form action="/?page=admin/alert-edit" method="post">

									<label for="alert_type">Alert Type:</label>
									<select class="form-control" name="alert_type">
										<option value="<?php echo $type; ?>"><?php echo ucfirst($type); ?></option>
										<option value="success">Success</option>
										<option value="error">Error</option>
										<option value="info">Info</option>
										<option value="warning">Warning</option>
									</select>

									<br>

									<label for="alert_message">Snippet:</label>
									<textarea class="form-control" cols="100" id="1" name="alert_message" rows="10"><?php echo $message; ?></textarea>

									<br>

									<div class="form-group pull-right">
										<input type="hidden" name="alert_id" value="<?php echo $id; ?>">
										<input type="hidden" name="edit" value="true">
										<input class="btn btn-info btn-large" type="submit" value="submit">
										<a class="btn btn-danger btn-large" href="index.php?page=admin/dashboard" type="button">cancel</a>
									</div>
								</form>
							</div><!-- / pannel body -->
						</div><!-- / pannel -->
					<!-- /row -->
					<script src="www/js/tinymce/tinymce.min.js"></script>
					<script>
					//Initialize TinyMce
					tinymce.init({
						selector:'textarea',
						relative_urls : false,
						remove_script_host : false,
						plugins: [
							"textpattern advlist autolink lists link image charmap print preview anchor",
							"searchreplace visualblocks code fullscreen",
							"insertdatetime media table contextmenu paste textcolor"
						],
						toolbar: "undo redo | styleselect | bold italic | forecolor backcolor | alignleft aligncenter alignright | bullist numlist | link jbimages | mybutton",
						/* setup : function(ed) {
							ed.addButton('mybutton', {
								title : 'Remove TinyMCE',
								image : 'bs/img/remove.gif',
								onclick : function remove() {
									// Add you own code to execute something on click
								   tinymce.remove('textarea');
								}
							});
						}*/
					});
					</script>
					<?php
				}
			}
			else {
				//can't view directly.
				echo
				'
				<div class="alert alert-danger">
					You have not selected any posts to edit! Redirecting...
				</div>
				<script>setTimeout(function () {window.location.href = "index.php?page=admin/news-manage";}, 2000);</script>
				';
			}
			?>


    	  <!-- / admin tab content here -->
		</div>
	</div>



	<?php
} else {
    // the user is not logged in. you can do whatever you want here.
    // for demonstration purposes, we simply show the "you are not logged in" view.
    header("Location: ?page=login");
}
?>
