<?php
// create a login object. when this object is created, it will do all login/logout stuff automatically
// so this single line handles the entire login process. in consequence, you can simply ...
$login = new Login();

// ... ask if we are logged in here:
if ($login->isUserLoggedIn() == true) {
    // the user is logged in. you can do whatever you want here.
	?>

		<div class="container">
		<?php
		
		/**
		 * A simple, clean and secure PHP Login Script / MINIMAL VERSION
		 * For more versions (one-file, advanced, framework-like) visit http://www.php-login.net
		 *
		 * Uses PHP SESSIONS, modern password-hashing and salting and gives the basic functions a proper login system needs.
		 *
		 * @author Panique
		 * @link https://github.com/panique/php-login-minimal/
		 * @license http://opensource.org/licenses/MIT MIT License
		 */
		
		// checking for minimum PHP version
		if (version_compare(PHP_VERSION, '5.3.7', '<')) {
		    exit("Sorry, Simple PHP Login does not run on a PHP version smaller than 5.3.7 !");
		} else if (version_compare(PHP_VERSION, '5.5.0', '<')) {
		    // if you are using PHP 5.3 or PHP 5.4 you have to include the password_api_compatibility_library.php
		    // (this library adds the PHP 5.5 password hashing functions to older versions of PHP)
		    require_once("lib/password_compatibility_library.php");
		}
		
		// create the registration object. when this object is created, it will do all registration stuff automatically
		// so this single line handles the entire registration process.
		$registration = new Registration();
		
		// show the register view (with the registration form, and messages/errors)
		?>
		
		<div class="row">
		    <h1>Register</h1>
		</div>
		
		<?php
		// show potential errors / feedback (from registration object)
		if (isset($registration)) {
		    if ($registration->errors) {
			   foreach ($registration->errors as $error) {
				  echo '<div class="row">' . bsAlert('error', $error) . '</div>';
			   }
		    }
		    if ($registration->messages) {
			   foreach ($registration->messages as $message) {
				  echo '<div class="row">' . bsAlert('success', $message) . '</div>';
			   }
		    }
		}
		?>
		
		<div class="row">
		    <!-- register form -->
		    <form method="post" action="?page=admin/register" name="registerform" class="form">
		
			   <!-- the user name input field uses a HTML5 pattern check -->
			   <div class="form-group">
				  <label for="login_input_username">Username (only letters and numbers, 2 to 64 characters)</label>
				  <input id="login_input_username" class="login_input form-control" type="text" pattern="[a-zA-Z0-9]{2,64}" name="user_name" required />
			   </div>
		
			   <!-- the email input field uses a HTML5 email type check -->
			   <div class="form-group">
				  <label for="login_input_email">User's email</label>
				  <input id="login_input_email" class="login_input form-control" type="email" name="user_email" required />
			   </div>
		
			   <div class="form-group">
				  <label for="login_input_password_new">Password (min. 6 characters)</label>
				  <input id="login_input_password_new" class="login_input form-control" type="password" name="user_password_new" pattern=".{6,}" required autocomplete="off" />
			   </div>
		
			   <div class="form-group">
				  <label for="login_input_password_repeat">Repeat password</label>
				  <input id="login_input_password_repeat" class="login_input form-control" type="password" name="user_password_repeat" pattern=".{6,}" required autocomplete="off" />
			   </div>
			   <div class="form-group pull-right">
				  <input type="submit"  name="register" value="Register" class="btn btn-default" />
			   </div>
		
		    </form>
		
		</div>
		
		</div>

	<?php
} else {
    // the user is not logged in. you can do whatever you want here.
    // for demonstration purposes, we simply show the "you are not logged in" view.
    header("Location: ?page=login");
}
?>
