<?php
// Grab our data from the database
// create add, edit, manage downloads pages... 

?>

<div class="container">
	<div class="row">
		<div class="col-md-12">	
			<h2>Downloads</h2>

			<?php
			$limit = 3; #item per page
			$page = (int) (!isset($_GET['p'])) ? 1 : $_GET['p'];

			# sql query
			$sql = "SELECT * FROM `downloads` ORDER BY `id` DESC";

			# find out query stat point
			$start = ($page * $limit) - $limit;

			# query for page navigation
			if( ($database->num_rows($sql)) > ($page * $limit) ){
				$next = ++$page;
			}

			$query = $sql . " LIMIT {$start}, {$limit}";

			if ($database->num_rows($query) > 0) {

				//show paginated list
				$results = $database->get_results( $query );
				
				echo'
					<div '. /*id="no-more-tables"*/' class="well overflowing">
						<table class="table table-bordered cf">
							<thead class="cf">
								<tr>
									<th>File Name</th>
									<th>Description</th>
									<th>Size</th>
									<th>Added</th>
									<th>MD5 Checksum</th>
									<th>Downloaded</th>
									<th></th>
									
								</tr>
							</thead>
							<tbody>
				';
				
				foreach( $results as $row )
				{

					echo'
								<tr>
									<td width="20%" data-title="">' . $row['filename'] . '</td>
									<td width="25%" data-title="">' . $row['description'] . '</td>
									<td width="10%" data-title="">' . humanFilesize($row['size']) . '</td>
									<td width="10%" data-title="">' . timeAgo(strtotime($row['date'])) . '</td>
									<td width="15%" data-title="">' . $row['md5checksum'] . '</td>
									<td width="10%" data-title="">' . $row['downloaded'] . ' time(s)</td>
					';
									if ($login->isUserLoggedIn() == true) 
									{
										echo'
										<td width="10%" data-title="">
											<a href="/?func=download&file=' . $row['filename'] . '"><button class="btn btn-info btn-xs"><span class="glyphicon glyphicon-circle-arrow-down"></span></button></a>
											<a href="?page=admin/downloads-edit&id=' . $row['id'] . '"><button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></button></a>
											<a onClick="return confirm(\'Are you sure you want to delete this item?\');" href="?page=admin/downloads-manage&action=delete&id=' . $row['id'] . '"><button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button></a>
										</td>
										';
									}
									else 
									{	
										
										echo'
										<td width="10%" data-title="">
											<a href="/?func=download&file=' . $row['filename'] . '"><button class="btn btn-info btn-xs">Download</button></a>
										</td>
										';
									}
					echo'
								</tr>
					';
				}
				echo'
							</tbody>
						</table>
					</div>
				';
			}
			else{
				//No posts
				echo '<div class="alert alert-danger">Sorry, there are no downloads! Check again later...</div>';
			}

			//page navigation
			if (isset($next)) {
				echo
				'
				<div class="downloads-more">
					<ul class="pager">
						<li class="next">
							<a href="index.php?page=admin/downloads-manage&p=' . $next . '">Next &rarr;</a>
						</li>
					</ul>
				</div>
				';
			}
			?>
		</div>
	</div>
</div>

<br>

<script>
/* $(document).ready(function() {

	$("#no-more-tables").each(function() {
		var nmtTable = $(this);
		var nmtHeadRow = nmtTable.find("thead tr");
		
		nmtTable.find("tbody tr").each(function() {
			var curRow = $(this);
			for (var i = 0; i < curRow.find("td").length; i++) {
				var rowSelector = "td:eq(" + i + ")";
				var headSelector = "th:eq(" + i + ")";
				curRow.find(rowSelector).attr('data-title', nmtHeadRow.find(headSelector).html());
			}
		});
	});
}); */
</script>