<div class="container">

    <div class="row">

        <!-- Left column -->
        <div class="col-md-3">

            <!-- Alert Widget -->
            <?php
                $sql= "SELECT * FROM `alert`";
                if ($database->num_rows($sql) > 0)
                {
                    $result = $database->get_results($sql);
                    foreach ( $result as $row )
                    {
                        if ($login->isUserLoggedIn() == true)
                        {
                            echo '<a href="/?page=admin/alert-manage" class="alt-link">' . bsAlert( $row['type'], $row['message'] . '<br> <small>' . timeAgo(strtotime($row['date'])) . '</small></a>' );
                        }
                        else
                        {
                            echo bsAlert( $row['type'], $row['message'] . '<br> <small>' . timeAgo(strtotime($row['date'])) . '</small>');
                        }
                    }
                }
                else
                {
                    echo bsAlert( 'success', 'There are no alerts at the moment.' . '<br> <small>' . timeAgo(strtotime($row['date'])) . '</small>');
                }
            ?>

            <!-- Online Widget -->
            <div class="onlineWidget alert alert-success black">
                <div class="panel-header">
                    <br>
                    <h2 class="panel-title text-center"> <span class="count"></span> visitor(s) online</h2>
                    <hr style="margin-bottom:1px !important;">
                </div>
                <div class="panel-body">
                    <div class="online-panel"></div>
                </div>
            </div>

        </div>

        <!-- Middle column -->
        <div class="col-md-6">

            <!-- Main Copy -->
            <div class="text-center alert alert-info">
                <br>
                <div id="google_translate_element"></div>
                <br>
                <p class="lead">
                    Owners of the 2011 MacBook Pro line of computers that are experiencing widespread GPU failures <i>will not be satisfied</i> until our machines are restored to <strong>working order</strong> through a replacement program at no cost to users.
                </p>
                <p><a class="btn btn-md btn-danger" role="button" onClick="trackAction(0);" href="?page=action">Take Action!</a></p>
            </div>

            <!-- YouTube Embed -->
            <div class="text-center alert alert-info">
                <!-- 4:3 aspect ratio -->
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" id="youTubePlayer" src="https://www.youtube.com/embed/sKn8D5cIU0g?rel=0&enablejsapi=1" allowfullscreen></iframe>
                    <script>
                        // This code loads the IFrame Player API code asynchronously
                        var tag = document.createElement('script');
                        tag.src = "http://www.youtube.com/iframe_api";
                        var firstScriptTag = document.getElementsByTagName('script')[0];
                        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

                        // This code is called by the YouTube API to create the player object
                        function onYouTubeIframeAPIReady(event) {
                            player = new YT.Player('youTubePlayer', {
                                events: {
                                    'onReady': onPlayerReady,
                                    'onStateChange': onPlayerStateChange
                                }
                            });

                            var pauseFlag = false;

                            function onPlayerReady(event) {
                                // do nothing, no tracking needed
                            }

                            function onPlayerStateChange(event) {
                                // track when user clicks to Play
                                if (event.data == YT.PlayerState.PLAYING) {
                                    ga('send', 'event', 'Video', 'Play', 'MBP2011 Video');
                                    pauseFlag = true;
                                }
                                // track when user clicks to Pause
                                if (event.data == YT.PlayerState.PAUSED && pauseFlag) {
                                    ga('send', 'event', 'Video', 'Paused', 'MBP2011 Video');
                                    pauseFlag = false;
                                }
                                // track when video ends
                                if (event.data == YT.PlayerState.ENDED) {
                                    ga('send', 'event', 'Video', 'Finish', 'MBP2011 Video');
                                }
                            }
                        }
                    </script>
                </div>
            </div>

        </div>

        <!-- Right column -->
        <div class="col-md-3">

            <!-- Recent Uploads -->
            <div class="photoWidget alert alert-success black">
                <div class="panel-header">
                    <br>
                    <h2 class="panel-title text-center">Recently Uploaded</h2>
                    <hr style="margin-bottom:1px !important;">
                </div>
                <div class="panel-body">
                    <?php
                    // Grab our data from the Amazon
                    // AWS S3 (Simple Storage System)

                    //Fetch XML image list...
                    $url = 'http://mbp2011.s3.amazonaws.com/';
                    $urlSmall = 'http://mbp2011.s3.amazonaws.com/small/';

                    //Parse XML image list to PHP object...
                    $xml = simplexml_load_file($url);

                    //For each XML object as PHP object
                    foreach( $xml->Contents as $xml )
                    {
                        //Match only the BREAKFREE filename object.
                        if ( preg_match('/^BREAKFREE/', $xml->Key ) )
                        {
                            //Gather filenames in array
                            $images[] = $xml->Key;
                        }

                    }
                    // how many images are there?
                    $img_count = count($images);

                    // how many to show on each page?
                    $per_page = 2;

                    // calculate pagination
                    $max_pages = ceil($img_count / $per_page);

                    $show = array_slice($images, - 6, - 1); //show last two uploads
                    //$show = array_slice($images, - 1); //show last upload

                    //display images
                    $i = 1;
                    foreach ($show as $image)
                    {
                        echo '<div id="div' . $i . '" class="display"><a class="popup-gallery" href="' .  $url . $image . '" alt="" target="_BLANK"><img class="img-responsive" src="' . $urlSmall . $image . '" alt="" /></a></div>';
                        $i++;
                    }
                    ?>
                </div>
            </div>

            <script>
                $(document).ready(function(){
                    // This function is executed once the document is loaded

                    // Caching the jQuery selectors:
                    var count = $('.onlineWidget .count');
                    var panel = $('.onlineWidget .online-panel');

                    count.load('/?func=online');
                    panel.load('/?func=geodata');

                    var activeDiv = 1;
                    showDiv(activeDiv);
                    var timer = setInterval(changeDiv, 5500);


                    function changeDiv() {
                        activeDiv++;
                        if (activeDiv == 6) {
                            activeDiv = 1;
                        }
                        showDiv(activeDiv);
                    }

                    function showDiv(num) {
                        $('div.display').hide();
                        $('#div' + num).fadeIn();
                    }


                });
            </script>

        </div>

    </div>

</div>
